2023-03-09T23:26:29.921+0800	INFO	instance/beat.go:640	Home path: [E:\code\云原生\git.imooc.com\dessple\pob] Config path: [E:\code\云原生\git.imooc.com\dessple\pob] Data path: [E:\code\云原生\git.imooc.com\dessple\pob\data] Logs path: [E:\code\云原生\git.imooc.com\dessple\pob\logs]
2023-03-09T23:26:29.921+0800	INFO	instance/beat.go:648	Beat ID: f781c3fd-0e4f-4897-a418-f8e76dba9b37
2023-03-09T23:26:29.922+0800	INFO	[beat]	instance/beat.go:976	Beat info	{"system_info": {"beat": {"path": {"config": "E:\\code\\云原生\\git.imooc.com\\dessple\\pob", "data": "E:\\code\\云原生\\git.imooc.com\\dessple\\pob\\data", "home": "E:\\code\\云原生\\git.imooc.com\\dessple\\pob", "logs": "E:\\code\\云原生\\git.imooc.com\\dessple\\pob\\logs"}, "type": "filebeat", "uuid": "f781c3fd-0e4f-4897-a418-f8e76dba9b37"}}}
2023-03-09T23:26:29.922+0800	INFO	[beat]	instance/beat.go:985	Build info	{"system_info": {"build": {"commit": "7aab6a9659749802201db8020c4f04b74cec2169", "libbeat": "7.9.3", "time": "2020-10-16T09:16:15.000Z", "version": "7.9.3"}}}
2023-03-09T23:26:29.922+0800	INFO	[beat]	instance/beat.go:988	Go runtime info	{"system_info": {"go": {"os":"windows","arch":"amd64","max_procs":12,"version":"go1.14.7"}}}
2023-03-09T23:26:29.999+0800	INFO	[beat]	instance/beat.go:992	Host info	{"system_info": {"host": {"architecture":"x86_64","boot_time":"2023-02-22T12:12:32.39+08:00","name":"DESKTOP-8K1IJ5A","ip":["fe80::2184:6ead:541:5295/64","169.254.23.90/16","fe80::9911:c532:6924:c868/64","172.31.144.1/20","fe80::5483:90c1:b30b:785e/64","169.254.244.105/16","fe80::35a9:1db8:a1f4:da6a/64","169.254.163.202/16","fe80::3318:2c57:4ae5:c3d8/64","192.168.142.1/24","fe80::bf70:9708:c69e:1b8/64","192.168.115.1/24","fd26:a241:87f4::d1f/128","fd26:a241:87f4:0:ce3d:e1bc:8bc0:100d/64","fd26:a241:87f4:0:6033:66cf:eaa9:9167/128","fd26:a241:87f4:0:d99c:5e73:3d70:9989/128","fd26:a241:87f4:0:f5d9:16bb:d810:9e93/128","fe80::ab2f:5bad:e890:55ea/64","192.168.1.128/24","fe80::99f4:b0e5:2e1d:d9a4/64","169.254.216.66/16","::1/128","127.0.0.1/8"],"kernel_version":"10.0.19041.2604 (WinBuild.160101.0800)","mac":["d8:bb:c1:4f:6c:c8","00:15:5d:fd:2b:60","e2:e1:a9:19:7a:8b","e0:e1:a9:19:7a:8b","00:50:56:c0:00:01","00:50:56:c0:00:08","e0:e1:a9:19:7a:8b","00:1a:7d:da:71:15"],"os":{"family":"windows","platform":"windows","name":"Windows 10 Pro","version":"10.0","major":10,"minor":0,"patch":0,"build":"19045.2604"},"timezone":"CST","timezone_offset_sec":28800,"id":"dc5c532d-a6b6-404d-a9b8-261c7f04c685"}}}
2023-03-09T23:26:29.999+0800	INFO	[beat]	instance/beat.go:1021	Process info	{"system_info": {"process": {"cwd": "E:\\code\\云原生\\git.imooc.com\\dessple\\pob", "exe": "D:\\filebeat-7.9.3-windows-x86_64\\filebeat.exe", "name": "filebeat.exe", "pid": 26464, "ppid": 1532, "start_time": "2023-03-09T23:26:29.745+0800"}}}
2023-03-09T23:26:29.999+0800	INFO	instance/beat.go:299	Setup Beat: filebeat; Version: 7.9.3
2023-03-09T23:26:30.000+0800	INFO	[publisher]	pipeline/module.go:113	Beat name: DESKTOP-8K1IJ5A
2023-03-09T23:26:30.000+0800	ERROR	fileset/modules.go:127	Not loading modules. Module directory not found: E:\code\云原生\git.imooc.com\dessple\pob\module
2023-03-09T23:26:30.000+0800	WARN	beater/filebeat.go:178	Filebeat is unable to load the Ingest Node pipelines for the configured modules because the Elasticsearch output is not configured/enabled. If you have already loaded the Ingest Node pipelines or are using Logstash pipelines, you can ignore this warning.
2023-03-09T23:26:30.000+0800	INFO	instance/beat.go:450	filebeat start running.
2023-03-09T23:26:30.000+0800	INFO	[monitoring]	log/log.go:118	Starting metrics logging every 30s
2023-03-09T23:26:30.000+0800	INFO	memlog/store.go:119	Loading data file of 'E:\code\云原生\git.imooc.com\dessple\pob\data\registry\filebeat' succeeded. Active transaction id=0
2023-03-09T23:26:30.001+0800	INFO	memlog/store.go:124	Finished loading transaction log file for 'E:\code\云原生\git.imooc.com\dessple\pob\data\registry\filebeat'. Active transaction id=7
2023-03-09T23:26:30.001+0800	WARN	beater/filebeat.go:381	Filebeat is unable to load the Ingest Node pipelines for the configured modules because the Elasticsearch output is not configured/enabled. If you have already loaded the Ingest Node pipelines or are using Logstash pipelines, you can ignore this warning.
2023-03-09T23:26:30.001+0800	INFO	[registrar]	registrar/registrar.go:109	States Loaded from registrar: 1
2023-03-09T23:26:30.001+0800	INFO	[crawler]	beater/crawler.go:71	Loading Inputs: 1
2023-03-09T23:26:30.001+0800	INFO	log/input.go:157	Configured paths: [E:\code\云原生\git.imooc.com\dessple\pob\*.log]
2023-03-09T23:26:30.001+0800	INFO	[crawler]	beater/crawler.go:141	Starting input (ID: 9579789163401830746)
2023-03-09T23:26:30.001+0800	INFO	[crawler]	beater/crawler.go:108	Loading and starting Inputs completed. Enabled inputs: 1
2023-03-09T23:26:30.009+0800	INFO	log/harvester.go:299	Harvester started for file: E:\code\云原生\git.imooc.com\dessple\pob\micro.log
2023-03-09T23:26:31.017+0800	INFO	[publisher_pipeline_output]	pipeline/output.go:143	Connecting to backoff(async(tcp://localhost:5044))
2023-03-09T23:26:31.017+0800	INFO	[publisher]	pipeline/retry.go:219	retryer: send unwait signal to consumer
2023-03-09T23:26:31.017+0800	INFO	[publisher]	pipeline/retry.go:223	  done
2023-03-09T23:26:36.164+0800	ERROR	[publisher_pipeline_output]	pipeline/output.go:154	Failed to connect to backoff(async(tcp://localhost:5044)): dial tcp 127.0.0.1:5044: connectex: No connection could be made because the target machine actively refused it.
2023-03-09T23:26:36.164+0800	INFO	[publisher_pipeline_output]	pipeline/output.go:145	Attempting to reconnect to backoff(async(tcp://localhost:5044)) with 1 reconnect attempt(s)
2023-03-09T23:26:36.164+0800	INFO	[publisher]	pipeline/retry.go:219	retryer: send unwait signal to consumer
2023-03-09T23:26:36.164+0800	INFO	[publisher]	pipeline/retry.go:223	  done
2023-03-09T23:26:42.517+0800	ERROR	[publisher_pipeline_output]	pipeline/output.go:154	Failed to connect to backoff(async(tcp://localhost:5044)): dial tcp [::1]:5044: connectex: No connection could be made because the target machine actively refused it.
2023-03-09T23:26:42.517+0800	INFO	[publisher_pipeline_output]	pipeline/output.go:145	Attempting to reconnect to backoff(async(tcp://localhost:5044)) with 2 reconnect attempt(s)
2023-03-09T23:26:42.517+0800	INFO	[publisher]	pipeline/retry.go:219	retryer: send unwait signal to consumer
2023-03-09T23:26:42.517+0800	INFO	[publisher]	pipeline/retry.go:223	  done
2023-03-09T23:26:52.962+0800	ERROR	[publisher_pipeline_output]	pipeline/output.go:154	Failed to connect to backoff(async(tcp://localhost:5044)): dial tcp 127.0.0.1:5044: connectex: No connection could be made because the target machine actively refused it.
2023-03-09T23:26:52.962+0800	INFO	[publisher_pipeline_output]	pipeline/output.go:145	Attempting to reconnect to backoff(async(tcp://localhost:5044)) with 3 reconnect attempt(s)
2023-03-09T23:26:52.962+0800	INFO	[publisher]	pipeline/retry.go:219	retryer: send unwait signal to consumer
2023-03-09T23:26:52.962+0800	INFO	[publisher]	pipeline/retry.go:223	  done
2023-03-09T23:27:00.000+0800	INFO	[monitoring]	log/log.go:145	Non-zero metrics in the last 30s	{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":46,"time":{"ms":46}},"total":{"ticks":108,"time":{"ms":108},"value":108},"user":{"ticks":62,"time":{"ms":62}}},"handles":{"open":237},"info":{"ephemeral_id":"70a9c63d-221d-42d5-add4-b5122cacad24","uptime":{"ms":30131}},"memstats":{"gc_next":15609792,"memory_alloc":8070376,"memory_total":36846424,"rss":48652288},"runtime":{"goroutines":28}},"filebeat":{"events":{"active":41,"added":43,"done":2},"harvester":{"files":{"1a7746ac-1940-4c30-a206-26912f98f78d":{"last_event_published_time":"2023-03-09T23:26:30.010Z","last_event_timestamp":"2023-03-09T23:26:30.010Z","name":"E:\\code\\云原生\\git.imooc.com\\dessple\\pob\\micro.log","read_offset":8646,"size":8646,"start_time":"2023-03-09T23:26:30.009Z"}},"open_files":1,"running":1,"started":1}},"libbeat":{"config":{"module":{"running":0}},"output":{"type":"logstash"},"pipeline":{"clients":1,"events":{"active":41,"filtered":2,"published":41,"retry":123,"total":43}}},"registrar":{"states":{"current":1,"update":2},"writes":{"success":2,"total":2}},"system":{"cpu":{"cores":12}}}}}
2023-03-09T23:27:07.776+0800	ERROR	[publisher_pipeline_output]	pipeline/output.go:154	Failed to connect to backoff(async(tcp://localhost:5044)): dial tcp 127.0.0.1:5044: connectex: No connection could be made because the target machine actively refused it.
2023-03-09T23:27:07.776+0800	INFO	[publisher_pipeline_output]	pipeline/output.go:145	Attempting to reconnect to backoff(async(tcp://localhost:5044)) with 4 reconnect attempt(s)
2023-03-09T23:27:07.776+0800	INFO	[publisher]	pipeline/retry.go:219	retryer: send unwait signal to consumer
2023-03-09T23:27:07.776+0800	INFO	[publisher]	pipeline/retry.go:223	  done
2023-03-09T23:27:30.011+0800	INFO	[monitoring]	log/log.go:145	Non-zero metrics in the last 30s	{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":46},"total":{"ticks":108,"value":108},"user":{"ticks":62}},"handles":{"open":236},"info":{"ephemeral_id":"70a9c63d-221d-42d5-add4-b5122cacad24","uptime":{"ms":60142}},"memstats":{"gc_next":15609792,"memory_alloc":8177552,"memory_total":36953600,"rss":20480},"runtime":{"goroutines":28}},"filebeat":{"harvester":{"open_files":1,"running":1}},"libbeat":{"config":{"module":{"running":0}},"pipeline":{"clients":1,"events":{"active":41,"retry":41}}},"registrar":{"states":{"current":1}}}}}
2023-03-09T23:27:41.626+0800	ERROR	[publisher_pipeline_output]	pipeline/output.go:154	Failed to connect to backoff(async(tcp://localhost:5044)): dial tcp [::1]:5044: connectex: No connection could be made because the target machine actively refused it.
2023-03-09T23:27:41.626+0800	INFO	[publisher_pipeline_output]	pipeline/output.go:145	Attempting to reconnect to backoff(async(tcp://localhost:5044)) with 5 reconnect attempt(s)
2023-03-09T23:27:41.626+0800	INFO	[publisher]	pipeline/retry.go:219	retryer: send unwait signal to consumer
2023-03-09T23:27:41.626+0800	INFO	[publisher]	pipeline/retry.go:223	  done
2023-03-09T23:28:00.012+0800	INFO	[monitoring]	log/log.go:145	Non-zero metrics in the last 30s	{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":46},"total":{"ticks":108,"value":108},"user":{"ticks":62}},"handles":{"open":237},"info":{"ephemeral_id":"70a9c63d-221d-42d5-add4-b5122cacad24","uptime":{"ms":90142}},"memstats":{"gc_next":15609792,"memory_alloc":8262872,"memory_total":37038920},"runtime":{"goroutines":28}},"filebeat":{"harvester":{"open_files":1,"running":1}},"libbeat":{"config":{"module":{"running":0}},"pipeline":{"clients":1,"events":{"active":41,"retry":41}}},"registrar":{"states":{"current":1}}}}}
2023-03-09T23:28:30.000+0800	INFO	[monitoring]	log/log.go:145	Non-zero metrics in the last 30s	{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":46},"total":{"ticks":108,"value":108},"user":{"ticks":62}},"handles":{"open":237},"info":{"ephemeral_id":"70a9c63d-221d-42d5-add4-b5122cacad24","uptime":{"ms":120131}},"memstats":{"gc_next":15609792,"memory_alloc":8560984,"memory_total":37337032},"runtime":{"goroutines":28}},"filebeat":{"events":{"active":3,"added":3},"harvester":{"files":{"1a7746ac-1940-4c30-a206-26912f98f78d":{"last_event_published_time":"2023-03-09T23:28:25.096Z","last_event_timestamp":"2023-03-09T23:28:25.096Z","read_offset":486}},"open_files":1,"running":1}},"libbeat":{"config":{"module":{"running":0}},"pipeline":{"clients":1,"events":{"active":44,"published":3,"total":3}}},"registrar":{"states":{"current":1}}}}}
2023-03-09T23:28:36.666+0800	ERROR	[publisher_pipeline_output]	pipeline/output.go:154	Failed to connect to backoff(async(tcp://localhost:5044)): dial tcp [::1]:5044: connectex: No connection could be made because the target machine actively refused it.
2023-03-09T23:28:36.666+0800	INFO	[publisher_pipeline_output]	pipeline/output.go:145	Attempting to reconnect to backoff(async(tcp://localhost:5044)) with 6 reconnect attempt(s)
2023-03-09T23:28:36.666+0800	INFO	[publisher]	pipeline/retry.go:219	retryer: send unwait signal to consumer
2023-03-09T23:28:36.666+0800	INFO	[publisher]	pipeline/retry.go:223	  done
2023-03-09T23:29:00.005+0800	INFO	[monitoring]	log/log.go:145	Non-zero metrics in the last 30s	{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":46},"total":{"ticks":108,"value":108},"user":{"ticks":62}},"handles":{"open":241},"info":{"ephemeral_id":"70a9c63d-221d-42d5-add4-b5122cacad24","uptime":{"ms":150135}},"memstats":{"gc_next":16371040,"memory_alloc":8224200,"memory_total":37437464,"rss":-5120000},"runtime":{"goroutines":28}},"filebeat":{"harvester":{"files":{"1a7746ac-1940-4c30-a206-26912f98f78d":{"size":486}},"open_files":1,"running":1}},"libbeat":{"config":{"module":{"running":0}},"pipeline":{"clients":1,"events":{"active":44,"retry":41}}},"registrar":{"states":{"current":1}}}}}
2023-03-09T23:29:30.006+0800	INFO	[monitoring]	log/log.go:145	Non-zero metrics in the last 30s	{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":46},"total":{"ticks":108,"value":108},"user":{"ticks":62}},"handles":{"open":245},"info":{"ephemeral_id":"70a9c63d-221d-42d5-add4-b5122cacad24","uptime":{"ms":180136}},"memstats":{"gc_next":16371040,"memory_alloc":8299024,"memory_total":37512288},"runtime":{"goroutines":28}},"filebeat":{"harvester":{"open_files":1,"running":1}},"libbeat":{"config":{"module":{"running":0}},"pipeline":{"clients":1,"events":{"active":44}}},"registrar":{"states":{"current":1}}}}}
2023-03-09T23:29:33.053+0800	ERROR	[publisher_pipeline_output]	pipeline/output.go:154	Failed to connect to backoff(async(tcp://localhost:5044)): dial tcp 127.0.0.1:5044: connectex: No connection could be made because the target machine actively refused it.
2023-03-09T23:29:33.053+0800	INFO	[publisher_pipeline_output]	pipeline/output.go:145	Attempting to reconnect to backoff(async(tcp://localhost:5044)) with 7 reconnect attempt(s)
2023-03-09T23:29:33.053+0800	INFO	[publisher]	pipeline/retry.go:219	retryer: send unwait signal to consumer
2023-03-09T23:29:33.053+0800	INFO	[publisher]	pipeline/retry.go:223	  done
2023-03-09T23:30:00.000+0800	INFO	[monitoring]	log/log.go:145	Non-zero metrics in the last 30s	{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":46},"total":{"ticks":108,"value":108},"user":{"ticks":62}},"handles":{"open":247},"info":{"ephemeral_id":"70a9c63d-221d-42d5-add4-b5122cacad24","uptime":{"ms":210131}},"memstats":{"gc_next":16371040,"memory_alloc":8385576,"memory_total":37598840,"rss":4096},"runtime":{"goroutines":28}},"filebeat":{"harvester":{"open_files":1,"running":1}},"libbeat":{"config":{"module":{"running":0}},"pipeline":{"clients":1,"events":{"active":44}}},"registrar":{"states":{"current":1}}}}}
2023-03-09T23:30:30.014+0800	INFO	[monitoring]	log/log.go:145	Non-zero metrics in the last 30s	{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":46},"total":{"ticks":108,"value":108},"user":{"ticks":62}},"handles":{"open":247},"info":{"ephemeral_id":"70a9c63d-221d-42d5-add4-b5122cacad24","uptime":{"ms":240144}},"memstats":{"gc_next":16371040,"memory_alloc":8460560,"memory_total":37673824},"runtime":{"goroutines":28}},"filebeat":{"harvester":{"open_files":1,"running":1}},"libbeat":{"config":{"module":{"running":0}},"pipeline":{"clients":1,"events":{"active":44}}},"registrar":{"states":{"current":1}}}}}
2023-03-09T23:30:35.676+0800	ERROR	[publisher_pipeline_output]	pipeline/output.go:154	Failed to connect to backoff(async(tcp://localhost:5044)): dial tcp 127.0.0.1:5044: connectex: No connection could be made because the target machine actively refused it.
2023-03-09T23:30:35.676+0800	INFO	[publisher_pipeline_output]	pipeline/output.go:145	Attempting to reconnect to backoff(async(tcp://localhost:5044)) with 8 reconnect attempt(s)
2023-03-09T23:30:35.676+0800	INFO	[publisher]	pipeline/retry.go:219	retryer: send unwait signal to consumer
2023-03-09T23:30:35.676+0800	INFO	[publisher]	pipeline/retry.go:223	  done
2023-03-09T23:31:00.012+0800	INFO	[monitoring]	log/log.go:145	Non-zero metrics in the last 30s	{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":46},"total":{"ticks":108,"value":108},"user":{"ticks":62}},"handles":{"open":247},"info":{"ephemeral_id":"70a9c63d-221d-42d5-add4-b5122cacad24","uptime":{"ms":270143}},"memstats":{"gc_next":16342336,"memory_alloc":8219024,"memory_total":37770376,"rss":-442368},"runtime":{"goroutines":28}},"filebeat":{"harvester":{"open_files":1,"running":1}},"libbeat":{"config":{"module":{"running":0}},"pipeline":{"clients":1,"events":{"active":44,"retry":41}}},"registrar":{"states":{"current":1}}}}}
2023-03-09T23:31:19.886+0800	ERROR	[publisher_pipeline_output]	pipeline/output.go:154	Failed to connect to backoff(async(tcp://localhost:5044)): dial tcp [::1]:5044: connectex: No connection could be made because the target machine actively refused it.
2023-03-09T23:31:19.886+0800	INFO	[publisher_pipeline_output]	pipeline/output.go:145	Attempting to reconnect to backoff(async(tcp://localhost:5044)) with 9 reconnect attempt(s)
2023-03-09T23:31:19.886+0800	INFO	[publisher]	pipeline/retry.go:219	retryer: send unwait signal to consumer
2023-03-09T23:31:19.886+0800	INFO	[publisher]	pipeline/retry.go:223	  done
2023-03-09T23:31:30.000+0800	INFO	[monitoring]	log/log.go:145	Non-zero metrics in the last 30s	{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":46},"total":{"ticks":108,"value":108},"user":{"ticks":62}},"handles":{"open":251},"info":{"ephemeral_id":"70a9c63d-221d-42d5-add4-b5122cacad24","uptime":{"ms":300131}},"memstats":{"gc_next":16342336,"memory_alloc":8299736,"memory_total":37851088,"rss":57344},"runtime":{"goroutines":28}},"filebeat":{"harvester":{"open_files":1,"running":1}},"libbeat":{"config":{"module":{"running":0}},"pipeline":{"clients":1,"events":{"active":44,"retry":3}}},"registrar":{"states":{"current":1}}}}}
2023-03-09T23:32:00.002+0800	INFO	[monitoring]	log/log.go:145	Non-zero metrics in the last 30s	{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":46},"total":{"ticks":108,"value":108},"user":{"ticks":62}},"handles":{"open":253},"info":{"ephemeral_id":"70a9c63d-221d-42d5-add4-b5122cacad24","uptime":{"ms":330133}},"memstats":{"gc_next":16342336,"memory_alloc":8371760,"memory_total":37923112},"runtime":{"goroutines":28}},"filebeat":{"harvester":{"open_files":1,"running":1}},"libbeat":{"config":{"module":{"running":0}},"pipeline":{"clients":1,"events":{"active":44}}},"registrar":{"states":{"current":1}}}}}
2023-03-09T23:32:22.792+0800	ERROR	[publisher_pipeline_output]	pipeline/output.go:154	Failed to connect to backoff(async(tcp://localhost:5044)): dial tcp [::1]:5044: connectex: No connection could be made because the target machine actively refused it.
2023-03-09T23:32:22.792+0800	INFO	[publisher_pipeline_output]	pipeline/output.go:145	Attempting to reconnect to backoff(async(tcp://localhost:5044)) with 10 reconnect attempt(s)
2023-03-09T23:32:22.792+0800	INFO	[publisher]	pipeline/retry.go:219	retryer: send unwait signal to consumer
2023-03-09T23:32:22.792+0800	INFO	[publisher]	pipeline/retry.go:223	  done
2023-03-09T23:32:30.009+0800	INFO	[monitoring]	log/log.go:145	Non-zero metrics in the last 30s	{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":46},"total":{"ticks":108,"value":108},"user":{"ticks":62}},"handles":{"open":255},"info":{"ephemeral_id":"70a9c63d-221d-42d5-add4-b5122cacad24","uptime":{"ms":360140}},"memstats":{"gc_next":16342336,"memory_alloc":8459944,"memory_total":38011296,"rss":4096},"runtime":{"goroutines":28}},"filebeat":{"harvester":{"open_files":1,"running":1}},"libbeat":{"config":{"module":{"running":0}},"pipeline":{"clients":1,"events":{"active":44,"retry":41}}},"registrar":{"states":{"current":1}}}}}
2023-03-09T23:33:00.013+0800	INFO	[monitoring]	log/log.go:145	Non-zero metrics in the last 30s	{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":46},"total":{"ticks":108,"value":108},"user":{"ticks":62}},"handles":{"open":255},"info":{"ephemeral_id":"70a9c63d-221d-42d5-add4-b5122cacad24","uptime":{"ms":390143}},"memstats":{"gc_next":16354592,"memory_alloc":8195600,"memory_total":38082248,"rss":-94208},"runtime":{"goroutines":28}},"filebeat":{"harvester":{"open_files":1,"running":1}},"libbeat":{"config":{"module":{"running":0}},"pipeline":{"clients":1,"events":{"active":44}}},"registrar":{"states":{"current":1}}}}}
2023-03-09T23:33:18.631+0800	ERROR	[publisher_pipeline_output]	pipeline/output.go:154	Failed to connect to backoff(async(tcp://localhost:5044)): dial tcp 127.0.0.1:5044: connectex: No connection could be made because the target machine actively refused it.
2023-03-09T23:33:18.631+0800	INFO	[publisher_pipeline_output]	pipeline/output.go:145	Attempting to reconnect to backoff(async(tcp://localhost:5044)) with 11 reconnect attempt(s)
2023-03-09T23:33:18.631+0800	INFO	[publisher]	pipeline/retry.go:219	retryer: send unwait signal to consumer
2023-03-09T23:33:18.631+0800	INFO	[publisher]	pipeline/retry.go:223	  done
2023-03-09T23:33:30.002+0800	INFO	[monitoring]	log/log.go:145	Non-zero metrics in the last 30s	{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":46},"total":{"ticks":108,"value":108},"user":{"ticks":62}},"handles":{"open":253},"info":{"ephemeral_id":"70a9c63d-221d-42d5-add4-b5122cacad24","uptime":{"ms":420133}},"memstats":{"gc_next":16354592,"memory_alloc":8289696,"memory_total":38176344,"rss":24576},"runtime":{"goroutines":28}},"filebeat":{"harvester":{"open_files":1,"running":1}},"libbeat":{"config":{"module":{"running":0}},"pipeline":{"clients":1,"events":{"active":44,"retry":3}}},"registrar":{"states":{"current":1}}}}}
2023-03-09T23:33:30.140+0800	INFO	log/harvester.go:330	File is inactive: E:\code\云原生\git.imooc.com\dessple\pob\micro.log. Closing because close_inactive of 5m0s reached.
2023-03-09T23:33:58.006+0800	ERROR	[publisher_pipeline_output]	pipeline/output.go:154	Failed to connect to backoff(async(tcp://localhost:5044)): dial tcp 127.0.0.1:5044: connectex: No connection could be made because the target machine actively refused it.
2023-03-09T23:33:58.006+0800	INFO	[publisher_pipeline_output]	pipeline/output.go:145	Attempting to reconnect to backoff(async(tcp://localhost:5044)) with 12 reconnect attempt(s)
2023-03-09T23:33:58.006+0800	INFO	[publisher]	pipeline/retry.go:219	retryer: send unwait signal to consumer
2023-03-09T23:33:58.006+0800	INFO	[publisher]	pipeline/retry.go:223	  done
2023-03-09T23:34:00.014+0800	INFO	[monitoring]	log/log.go:145	Non-zero metrics in the last 30s	{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":46},"total":{"ticks":108,"value":108},"user":{"ticks":62}},"handles":{"open":255},"info":{"ephemeral_id":"70a9c63d-221d-42d5-add4-b5122cacad24","uptime":{"ms":450144}},"memstats":{"gc_next":16354592,"memory_alloc":8380680,"memory_total":38267328,"rss":16384},"runtime":{"goroutines":24}},"filebeat":{"events":{"active":1,"added":1},"harvester":{"closed":1,"open_files":0,"running":0}},"libbeat":{"config":{"module":{"running":0}},"pipeline":{"clients":1,"events":{"active":44,"filtered":1,"retry":41,"total":1}}},"registrar":{"states":{"current":1}}}}}
2023-03-09T23:34:20.147+0800	INFO	log/harvester.go:299	Harvester started for file: E:\code\云原生\git.imooc.com\dessple\pob\micro.log
2023-03-09T23:34:30.001+0800	INFO	[monitoring]	log/log.go:145	Non-zero metrics in the last 30s	{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":46},"total":{"ticks":108,"value":108},"user":{"ticks":62}},"handles":{"open":257},"info":{"ephemeral_id":"70a9c63d-221d-42d5-add4-b5122cacad24","uptime":{"ms":480132}},"memstats":{"gc_next":16354592,"memory_alloc":8723008,"memory_total":38609656,"rss":172032},"runtime":{"goroutines":28}},"filebeat":{"events":{"active":4,"added":4},"harvester":{"files":{"eb254d42-800d-4ea7-a838-2996a805007e":{"last_event_published_time":"2023-03-09T23:34:20.147Z","last_event_timestamp":"2023-03-09T23:34:20.147Z","name":"E:\\code\\云原生\\git.imooc.com\\dessple\\pob\\micro.log","read_offset":9618,"size":9618,"start_time":"2023-03-09T23:34:20.147Z"}},"open_files":1,"running":1,"started":1}},"libbeat":{"config":{"module":{"running":0}},"pipeline":{"clients":1,"events":{"active":47,"filtered":1,"published":3,"total":4}}},"registrar":{"states":{"current":1}}}}}
2023-03-09T23:34:52.278+0800	ERROR	[publisher_pipeline_output]	pipeline/output.go:154	Failed to connect to backoff(async(tcp://localhost:5044)): dial tcp [::1]:5044: connectex: No connection could be made because the target machine actively refused it.
2023-03-09T23:34:52.278+0800	INFO	[publisher_pipeline_output]	pipeline/output.go:145	Attempting to reconnect to backoff(async(tcp://localhost:5044)) with 13 reconnect attempt(s)
2023-03-09T23:34:52.278+0800	INFO	[publisher]	pipeline/retry.go:219	retryer: send unwait signal to consumer
2023-03-09T23:34:52.278+0800	INFO	[publisher]	pipeline/retry.go:223	  done
2023-03-09T23:35:00.006+0800	INFO	[monitoring]	log/log.go:145	Non-zero metrics in the last 30s	{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":46},"total":{"ticks":108,"value":108},"user":{"ticks":62}},"handles":{"open":259},"info":{"ephemeral_id":"70a9c63d-221d-42d5-add4-b5122cacad24","uptime":{"ms":510137}},"memstats":{"gc_next":16773504,"memory_alloc":8486712,"memory_total":38766648,"rss":65536},"runtime":{"goroutines":28}},"filebeat":{"events":{"active":6,"added":6},"harvester":{"files":{"eb254d42-800d-4ea7-a838-2996a805007e":{"last_event_published_time":"2023-03-09T23:34:38.174Z","last_event_timestamp":"2023-03-09T23:34:38.174Z","read_offset":972,"size":972}},"open_files":1,"running":1}},"libbeat":{"config":{"module":{"running":0}},"pipeline":{"clients":1,"events":{"active":53,"published":6,"retry":3,"total":6}}},"registrar":{"states":{"current":1}}}}}
2023-03-09T23:35:30.010+0800	INFO	[monitoring]	log/log.go:145	Non-zero metrics in the last 30s	{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":46},"total":{"ticks":108,"value":108},"user":{"ticks":62}},"handles":{"open":257},"info":{"ephemeral_id":"70a9c63d-221d-42d5-add4-b5122cacad24","uptime":{"ms":540141}},"memstats":{"gc_next":16773504,"memory_alloc":8567024,"memory_total":38846960,"rss":28672},"runtime":{"goroutines":28}},"filebeat":{"harvester":{"open_files":1,"running":1}},"libbeat":{"config":{"module":{"running":0}},"pipeline":{"clients":1,"events":{"active":53}}},"registrar":{"states":{"current":1}}}}}
2023-03-09T23:35:46.407+0800	ERROR	[publisher_pipeline_output]	pipeline/output.go:154	Failed to connect to backoff(async(tcp://localhost:5044)): dial tcp [::1]:5044: connectex: No connection could be made because the target machine actively refused it.
2023-03-09T23:35:46.407+0800	INFO	[publisher_pipeline_output]	pipeline/output.go:145	Attempting to reconnect to backoff(async(tcp://localhost:5044)) with 14 reconnect attempt(s)
2023-03-09T23:35:46.408+0800	INFO	[publisher]	pipeline/retry.go:213	retryer: send wait signal to consumer
2023-03-09T23:35:46.408+0800	INFO	[publisher]	pipeline/retry.go:217	  done
2023-03-09T23:36:00.014+0800	INFO	[monitoring]	log/log.go:145	Non-zero metrics in the last 30s	{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":46},"total":{"ticks":108,"value":108},"user":{"ticks":62}},"handles":{"open":261},"info":{"ephemeral_id":"70a9c63d-221d-42d5-add4-b5122cacad24","uptime":{"ms":570144}},"memstats":{"gc_next":16773504,"memory_alloc":8850360,"memory_total":39130296,"rss":204800},"runtime":{"goroutines":28}},"filebeat":{"harvester":{"open_files":1,"running":1}},"libbeat":{"config":{"module":{"running":0}},"pipeline":{"clients":1,"events":{"active":53}}},"registrar":{"states":{"current":1}}}}}
2023-03-09T23:36:23.086+0800	ERROR	[publisher_pipeline_output]	pipeline/output.go:154	Failed to connect to backoff(async(tcp://localhost:5044)): dial tcp [::1]:5044: connectex: No connection could be made because the target machine actively refused it.
2023-03-09T23:36:23.086+0800	INFO	[publisher_pipeline_output]	pipeline/output.go:145	Attempting to reconnect to backoff(async(tcp://localhost:5044)) with 15 reconnect attempt(s)
2023-03-09T23:36:23.086+0800	INFO	[publisher]	pipeline/retry.go:219	retryer: send unwait signal to consumer
2023-03-09T23:36:23.086+0800	INFO	[publisher]	pipeline/retry.go:223	  done
2023-03-09T23:36:23.086+0800	INFO	[publisher]	pipeline/retry.go:213	retryer: send wait signal to consumer
2023-03-09T23:36:23.086+0800	INFO	[publisher]	pipeline/retry.go:217	  done
2023-03-09T23:36:30.006+0800	INFO	[monitoring]	log/log.go:145	Non-zero metrics in the last 30s	{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":46},"total":{"ticks":108,"value":108},"user":{"ticks":62}},"handles":{"open":261},"info":{"ephemeral_id":"70a9c63d-221d-42d5-add4-b5122cacad24","uptime":{"ms":600136}},"memstats":{"gc_next":16773504,"memory_alloc":8932640,"memory_total":39212576,"rss":12288},"runtime":{"goroutines":28}},"filebeat":{"harvester":{"open_files":1,"running":1}},"libbeat":{"config":{"module":{"running":0}},"pipeline":{"clients":1,"events":{"active":53,"retry":41}}},"registrar":{"states":{"current":1}}}}}
2023-03-09T23:37:00.000+0800	INFO	[monitoring]	log/log.go:145	Non-zero metrics in the last 30s	{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":46},"total":{"ticks":108,"value":108},"user":{"ticks":62}},"handles":{"open":261},"info":{"ephemeral_id":"70a9c63d-221d-42d5-add4-b5122cacad24","uptime":{"ms":630131}},"memstats":{"gc_next":17184720,"memory_alloc":8615416,"memory_total":39287776,"rss":86016},"runtime":{"goroutines":28}},"filebeat":{"harvester":{"open_files":1,"running":1}},"libbeat":{"config":{"module":{"running":0}},"pipeline":{"clients":1,"events":{"active":53}}},"registrar":{"states":{"current":1}}}}}
2023-03-09T23:37:04.021+0800	ERROR	[publisher_pipeline_output]	pipeline/output.go:154	Failed to connect to backoff(async(tcp://localhost:5044)): dial tcp [::1]:5044: connectex: No connection could be made because the target machine actively refused it.
2023-03-09T23:37:04.021+0800	INFO	[publisher_pipeline_output]	pipeline/output.go:145	Attempting to reconnect to backoff(async(tcp://localhost:5044)) with 16 reconnect attempt(s)
2023-03-09T23:37:04.021+0800	INFO	[publisher]	pipeline/retry.go:219	retryer: send unwait signal to consumer
2023-03-09T23:37:04.021+0800	INFO	[publisher]	pipeline/retry.go:223	  done
2023-03-09T23:37:04.021+0800	INFO	[publisher]	pipeline/retry.go:213	retryer: send wait signal to consumer
2023-03-09T23:37:04.021+0800	INFO	[publisher]	pipeline/retry.go:217	  done
2023-03-09T23:37:30.000+0800	INFO	[monitoring]	log/log.go:145	Non-zero metrics in the last 30s	{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":46},"total":{"ticks":108,"value":108},"user":{"ticks":62}},"handles":{"open":262},"info":{"ephemeral_id":"70a9c63d-221d-42d5-add4-b5122cacad24","uptime":{"ms":660131}},"memstats":{"gc_next":17184720,"memory_alloc":8741440,"memory_total":39413800,"rss":24576},"runtime":{"goroutines":28}},"filebeat":{"events":{"active":3,"added":3},"harvester":{"files":{"eb254d42-800d-4ea7-a838-2996a805007e":{"last_event_published_time":"2023-03-09T23:37:13.239Z","last_event_timestamp":"2023-03-09T23:37:13.239Z","read_offset":486,"size":486}},"open_files":1,"running":1}},"libbeat":{"config":{"module":{"running":0}},"pipeline":{"clients":1,"events":{"active":56,"published":3,"retry":3,"total":3}}},"registrar":{"states":{"current":1}}}}}
2023-03-09T23:37:55.109+0800	ERROR	[publisher_pipeline_output]	pipeline/output.go:154	Failed to connect to backoff(async(tcp://localhost:5044)): dial tcp [::1]:5044: connectex: No connection could be made because the target machine actively refused it.
2023-03-09T23:37:55.109+0800	INFO	[publisher_pipeline_output]	pipeline/output.go:145	Attempting to reconnect to backoff(async(tcp://localhost:5044)) with 17 reconnect attempt(s)
2023-03-09T23:37:55.109+0800	INFO	[publisher]	pipeline/retry.go:219	retryer: send unwait signal to consumer
2023-03-09T23:37:55.109+0800	INFO	[publisher]	pipeline/retry.go:223	  done
2023-03-09T23:37:55.109+0800	INFO	[publisher]	pipeline/retry.go:213	retryer: send wait signal to consumer
2023-03-09T23:37:55.109+0800	INFO	[publisher]	pipeline/retry.go:217	  done
2023-03-09T23:38:00.005+0800	INFO	[monitoring]	log/log.go:145	Non-zero metrics in the last 30s	{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":46},"total":{"ticks":108,"value":108},"user":{"ticks":62}},"handles":{"open":260},"info":{"ephemeral_id":"70a9c63d-221d-42d5-add4-b5122cacad24","uptime":{"ms":690135}},"memstats":{"gc_next":17184720,"memory_alloc":8892600,"memory_total":39564960},"runtime":{"goroutines":28}},"filebeat":{"events":{"active":6,"added":6},"harvester":{"files":{"eb254d42-800d-4ea7-a838-2996a805007e":{"last_event_published_time":"2023-03-09T23:37:53.267Z","last_event_timestamp":"2023-03-09T23:37:53.267Z","read_offset":2210,"size":1726}},"open_files":1,"running":1}},"libbeat":{"config":{"module":{"running":0}},"pipeline":{"clients":1,"events":{"active":62,"published":6,"retry":3,"total":6}}},"registrar":{"states":{"current":1}}}}}
2023-03-09T23:38:30.000+0800	INFO	[monitoring]	log/log.go:145	Non-zero metrics in the last 30s	{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":46},"total":{"ticks":108,"value":108},"user":{"ticks":62}},"handles":{"open":262},"info":{"ephemeral_id":"70a9c63d-221d-42d5-add4-b5122cacad24","uptime":{"ms":720131}},"memstats":{"gc_next":17184720,"memory_alloc":8973296,"memory_total":39645656},"runtime":{"goroutines":28}},"filebeat":{"harvester":{"files":{"eb254d42-800d-4ea7-a838-2996a805007e":{"size":484}},"open_files":1,"running":1}},"libbeat":{"config":{"module":{"running":0}},"pipeline":{"clients":1,"events":{"active":62}}},"registrar":{"states":{"current":1}}}}}
2023-03-09T23:38:37.855+0800	ERROR	[publisher_pipeline_output]	pipeline/output.go:154	Failed to connect to backoff(async(tcp://localhost:5044)): dial tcp [::1]:5044: connectex: No connection could be made because the target machine actively refused it.
2023-03-09T23:38:37.855+0800	INFO	[publisher_pipeline_output]	pipeline/output.go:145	Attempting to reconnect to backoff(async(tcp://localhost:5044)) with 18 reconnect attempt(s)
2023-03-09T23:39:00.001+0800	INFO	[monitoring]	log/log.go:145	Non-zero metrics in the last 30s	{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":46},"total":{"ticks":108,"value":108},"user":{"ticks":62}},"handles":{"open":262},"info":{"ephemeral_id":"70a9c63d-221d-42d5-add4-b5122cacad24","uptime":{"ms":750131}},"memstats":{"gc_next":17202928,"memory_alloc":8646976,"memory_total":39744184,"rss":86016},"runtime":{"goroutines":28}},"filebeat":{"harvester":{"open_files":1,"running":1}},"libbeat":{"config":{"module":{"running":0}},"pipeline":{"clients":1,"events":{"active":62}}},"registrar":{"states":{"current":1}}}}}
2023-03-09T23:39:30.003+0800	INFO	[monitoring]	log/log.go:145	Non-zero metrics in the last 30s	{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":46},"total":{"ticks":108,"value":108},"user":{"ticks":62}},"handles":{"open":262},"info":{"ephemeral_id":"70a9c63d-221d-42d5-add4-b5122cacad24","uptime":{"ms":780133}},"memstats":{"gc_next":17202928,"memory_alloc":8730392,"memory_total":39827600,"rss":45056},"runtime":{"goroutines":28}},"filebeat":{"harvester":{"open_files":1,"running":1}},"libbeat":{"config":{"module":{"running":0}},"pipeline":{"clients":1,"events":{"active":62}}},"registrar":{"states":{"current":1}}}}}
2023-03-09T23:39:36.976+0800	ERROR	[publisher_pipeline_output]	pipeline/output.go:154	Failed to connect to backoff(async(tcp://localhost:5044)): dial tcp 127.0.0.1:5044: connectex: No connection could be made because the target machine actively refused it.
2023-03-09T23:39:36.976+0800	INFO	[publisher_pipeline_output]	pipeline/output.go:145	Attempting to reconnect to backoff(async(tcp://localhost:5044)) with 19 reconnect attempt(s)
2023-03-09T23:39:36.976+0800	INFO	[publisher]	pipeline/retry.go:213	retryer: send wait signal to consumer
2023-03-09T23:39:36.976+0800	INFO	[publisher]	pipeline/retry.go:217	  done
2023-03-09T23:40:00.008+0800	INFO	[monitoring]	log/log.go:145	Non-zero metrics in the last 30s	{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":46},"total":{"ticks":108,"value":108},"user":{"ticks":62}},"handles":{"open":262},"info":{"ephemeral_id":"70a9c63d-221d-42d5-add4-b5122cacad24","uptime":{"ms":810138}},"memstats":{"gc_next":17202928,"memory_alloc":8810208,"memory_total":39907416,"rss":8192},"runtime":{"goroutines":28}},"filebeat":{"harvester":{"open_files":1,"running":1}},"libbeat":{"config":{"module":{"running":0}},"pipeline":{"clients":1,"events":{"active":62,"retry":41}}},"registrar":{"states":{"current":1}}}}}
2023-03-09T23:40:30.007+0800	INFO	[monitoring]	log/log.go:145	Non-zero metrics in the last 30s	{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":46},"total":{"ticks":108,"value":108},"user":{"ticks":62}},"handles":{"open":266},"info":{"ephemeral_id":"70a9c63d-221d-42d5-add4-b5122cacad24","uptime":{"ms":840138}},"memstats":{"gc_next":17202928,"memory_alloc":8885368,"memory_total":39982576,"rss":-3379200},"runtime":{"goroutines":28}},"filebeat":{"harvester":{"open_files":1,"running":1}},"libbeat":{"config":{"module":{"running":0}},"pipeline":{"clients":1,"events":{"active":62}}},"registrar":{"states":{"current":1}}}}}
2023-03-09T23:40:38.618+0800	ERROR	[publisher_pipeline_output]	pipeline/output.go:154	Failed to connect to backoff(async(tcp://localhost:5044)): dial tcp 127.0.0.1:5044: connectex: No connection could be made because the target machine actively refused it.
2023-03-09T23:40:38.618+0800	INFO	[publisher_pipeline_output]	pipeline/output.go:145	Attempting to reconnect to backoff(async(tcp://localhost:5044)) with 20 reconnect attempt(s)
2023-03-09T23:40:38.618+0800	INFO	[publisher]	pipeline/retry.go:213	retryer: send wait signal to consumer
2023-03-09T23:40:38.618+0800	INFO	[publisher]	pipeline/retry.go:217	  done
2023-03-09T23:41:00.001+0800	INFO	[monitoring]	log/log.go:145	Non-zero metrics in the last 30s	{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":46},"total":{"ticks":108,"value":108},"user":{"ticks":62}},"handles":{"open":266},"info":{"ephemeral_id":"70a9c63d-221d-42d5-add4-b5122cacad24","uptime":{"ms":870131}},"memstats":{"gc_next":17209824,"memory_alloc":8643128,"memory_total":40072800,"rss":1679360},"runtime":{"goroutines":28}},"filebeat":{"harvester":{"open_files":1,"running":1}},"libbeat":{"config":{"module":{"running":0}},"pipeline":{"clients":1,"events":{"active":62,"retry":3}}},"registrar":{"states":{"current":1}}}}}
2023-03-09T23:41:29.155+0800	ERROR	[publisher_pipeline_output]	pipeline/output.go:154	Failed to connect to backoff(async(tcp://localhost:5044)): dial tcp [::1]:5044: connectex: No connection could be made because the target machine actively refused it.
2023-03-09T23:41:29.155+0800	INFO	[publisher_pipeline_output]	pipeline/output.go:145	Attempting to reconnect to backoff(async(tcp://localhost:5044)) with 21 reconnect attempt(s)
2023-03-09T23:41:29.155+0800	INFO	[publisher]	pipeline/retry.go:213	retryer: send wait signal to consumer
2023-03-09T23:41:29.155+0800	INFO	[publisher]	pipeline/retry.go:217	  done
2023-03-09T23:41:30.013+0800	INFO	[monitoring]	log/log.go:145	Non-zero metrics in the last 30s	{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":46},"total":{"ticks":108,"value":108},"user":{"ticks":62}},"handles":{"open":267},"info":{"ephemeral_id":"70a9c63d-221d-42d5-add4-b5122cacad24","uptime":{"ms":900144}},"memstats":{"gc_next":17209824,"memory_alloc":8725152,"memory_total":40154824,"rss":20480},"runtime":{"goroutines":29}},"filebeat":{"harvester":{"open_files":1,"running":1}},"libbeat":{"config":{"module":{"running":0}},"pipeline":{"clients":1,"events":{"active":62,"retry":3}}},"registrar":{"states":{"current":1}}}}}
2023-03-09T23:42:00.013+0800	INFO	[monitoring]	log/log.go:145	Non-zero metrics in the last 30s	{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":46},"total":{"ticks":108,"value":108},"user":{"ticks":62}},"handles":{"open":266},"info":{"ephemeral_id":"70a9c63d-221d-42d5-add4-b5122cacad24","uptime":{"ms":930144}},"memstats":{"gc_next":17209824,"memory_alloc":8805048,"memory_total":40234720,"rss":4096},"runtime":{"goroutines":28}},"filebeat":{"harvester":{"open_files":1,"running":1}},"libbeat":{"config":{"module":{"running":0}},"pipeline":{"clients":1,"events":{"active":62}}},"registrar":{"states":{"current":1}}}}}
2023-03-09T23:42:18.070+0800	ERROR	[publisher_pipeline_output]	pipeline/output.go:154	Failed to connect to backoff(async(tcp://localhost:5044)): dial tcp 127.0.0.1:5044: connectex: No connection could be made because the target machine actively refused it.
2023-03-09T23:42:18.070+0800	INFO	[publisher_pipeline_output]	pipeline/output.go:145	Attempting to reconnect to backoff(async(tcp://localhost:5044)) with 22 reconnect attempt(s)
2023-03-09T23:42:18.070+0800	INFO	[publisher]	pipeline/retry.go:213	retryer: send wait signal to consumer
2023-03-09T23:42:18.070+0800	INFO	[publisher]	pipeline/retry.go:217	  done
2023-03-09T23:42:30.007+0800	INFO	[monitoring]	log/log.go:145	Non-zero metrics in the last 30s	{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":46},"total":{"ticks":108,"value":108},"user":{"ticks":62}},"handles":{"open":264},"info":{"ephemeral_id":"70a9c63d-221d-42d5-add4-b5122cacad24","uptime":{"ms":960138}},"memstats":{"gc_next":17209824,"memory_alloc":8886944,"memory_total":40316616,"rss":8192},"runtime":{"goroutines":28}},"filebeat":{"harvester":{"open_files":1,"running":1}},"libbeat":{"config":{"module":{"running":0}},"pipeline":{"clients":1,"events":{"active":62,"retry":6}}},"registrar":{"states":{"current":1}}}}}
2023-03-09T23:42:58.486+0800	INFO	log/harvester.go:330	File is inactive: E:\code\云原生\git.imooc.com\dessple\pob\micro.log. Closing because close_inactive of 5m0s reached.
2023-03-09T23:43:00.004+0800	INFO	[monitoring]	log/log.go:145	Non-zero metrics in the last 30s	{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":46},"total":{"ticks":108,"value":108},"user":{"ticks":62}},"handles":{"open":265},"info":{"ephemeral_id":"70a9c63d-221d-42d5-add4-b5122cacad24","uptime":{"ms":990134}},"memstats":{"gc_next":17206464,"memory_alloc":8639448,"memory_total":40405880,"rss":-32768},"runtime":{"goroutines":23}},"filebeat":{"events":{"active":1,"added":1},"harvester":{"closed":1,"open_files":0,"running":0}},"libbeat":{"config":{"module":{"running":0}},"pipeline":{"clients":1,"events":{"active":62,"filtered":1,"total":1}}},"registrar":{"states":{"current":1}}}}}
2023-03-09T23:43:03.737+0800	ERROR	[publisher_pipeline_output]	pipeline/output.go:154	Failed to connect to backoff(async(tcp://localhost:5044)): dial tcp [::1]:5044: connectex: No connection could be made because the target machine actively refused it.
2023-03-09T23:43:03.737+0800	INFO	[publisher_pipeline_output]	pipeline/output.go:145	Attempting to reconnect to backoff(async(tcp://localhost:5044)) with 23 reconnect attempt(s)
2023-03-09T23:43:03.737+0800	INFO	[publisher]	pipeline/retry.go:213	retryer: send wait signal to consumer
2023-03-09T23:43:03.737+0800	INFO	[publisher]	pipeline/retry.go:217	  done
2023-03-09T23:43:30.003+0800	INFO	[monitoring]	log/log.go:145	Non-zero metrics in the last 30s	{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":46},"total":{"ticks":108,"value":108},"user":{"ticks":62}},"handles":{"open":265},"info":{"ephemeral_id":"70a9c63d-221d-42d5-add4-b5122cacad24","uptime":{"ms":1020134}},"memstats":{"gc_next":17206464,"memory_alloc":8717744,"memory_total":40484176,"rss":24576},"runtime":{"goroutines":23}},"filebeat":{"harvester":{"open_files":0,"running":0}},"libbeat":{"config":{"module":{"running":0}},"pipeline":{"clients":1,"events":{"active":62,"retry":41}}},"registrar":{"states":{"current":1}}}}}
2023-03-09T23:43:51.783+0800	ERROR	[publisher_pipeline_output]	pipeline/output.go:154	Failed to connect to backoff(async(tcp://localhost:5044)): dial tcp [::1]:5044: connectex: No connection could be made because the target machine actively refused it.
2023-03-09T23:43:51.783+0800	INFO	[publisher_pipeline_output]	pipeline/output.go:145	Attempting to reconnect to backoff(async(tcp://localhost:5044)) with 24 reconnect attempt(s)
2023-03-09T23:43:51.783+0800	INFO	[publisher]	pipeline/retry.go:213	retryer: send wait signal to consumer
2023-03-09T23:43:51.783+0800	INFO	[publisher]	pipeline/retry.go:217	  done
2023-03-09T23:44:00.000+0800	INFO	[monitoring]	log/log.go:145	Non-zero metrics in the last 30s	{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":46},"total":{"ticks":108,"value":108},"user":{"ticks":62}},"handles":{"open":265},"info":{"ephemeral_id":"70a9c63d-221d-42d5-add4-b5122cacad24","uptime":{"ms":1050131}},"memstats":{"gc_next":17206464,"memory_alloc":8798088,"memory_total":40564520},"runtime":{"goroutines":23}},"filebeat":{"harvester":{"open_files":0,"running":0}},"libbeat":{"config":{"module":{"running":0}},"pipeline":{"clients":1,"events":{"active":62,"retry":3}}},"registrar":{"states":{"current":1}}}}}
2023-03-09T23:44:28.417+0800	ERROR	[publisher_pipeline_output]	pipeline/output.go:154	Failed to connect to backoff(async(tcp://localhost:5044)): dial tcp 127.0.0.1:5044: connectex: No connection could be made because the target machine actively refused it.
2023-03-09T23:44:28.417+0800	INFO	[publisher_pipeline_output]	pipeline/output.go:145	Attempting to reconnect to backoff(async(tcp://localhost:5044)) with 25 reconnect attempt(s)
2023-03-09T23:44:28.417+0800	INFO	[publisher]	pipeline/retry.go:213	retryer: send wait signal to consumer
2023-03-09T23:44:28.417+0800	INFO	[publisher]	pipeline/retry.go:217	  done
2023-03-09T23:44:30.006+0800	INFO	[monitoring]	log/log.go:145	Non-zero metrics in the last 30s	{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":46},"total":{"ticks":108,"value":108},"user":{"ticks":62}},"handles":{"open":264},"info":{"ephemeral_id":"70a9c63d-221d-42d5-add4-b5122cacad24","uptime":{"ms":1080136}},"memstats":{"gc_next":17206464,"memory_alloc":8886736,"memory_total":40653168,"rss":4096},"runtime":{"goroutines":24}},"filebeat":{"harvester":{"open_files":0,"running":0}},"libbeat":{"config":{"module":{"running":0}},"pipeline":{"clients":1,"events":{"active":62,"retry":3}}},"registrar":{"states":{"current":1}}}}}
2023-03-09T23:45:00.000+0800	INFO	[monitoring]	log/log.go:145	Non-zero metrics in the last 30s	{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":46},"total":{"ticks":108,"value":108},"user":{"ticks":62}},"handles":{"open":265},"info":{"ephemeral_id":"70a9c63d-221d-42d5-add4-b5122cacad24","uptime":{"ms":1110131}},"memstats":{"gc_next":17136864,"memory_alloc":8592624,"memory_total":40722968,"rss":69632},"runtime":{"goroutines":23}},"filebeat":{"harvester":{"open_files":0,"running":0}},"libbeat":{"config":{"module":{"running":0}},"pipeline":{"clients":1,"events":{"active":62}}},"registrar":{"states":{"current":1}}}}}
2023-03-09T23:45:16.372+0800	ERROR	[publisher_pipeline_output]	pipeline/output.go:154	Failed to connect to backoff(async(tcp://localhost:5044)): dial tcp 127.0.0.1:5044: connectex: No connection could be made because the target machine actively refused it.
2023-03-09T23:45:16.372+0800	INFO	[publisher_pipeline_output]	pipeline/output.go:145	Attempting to reconnect to backoff(async(tcp://localhost:5044)) with 26 reconnect attempt(s)
2023-03-09T23:45:16.372+0800	INFO	[publisher]	pipeline/retry.go:213	retryer: send wait signal to consumer
2023-03-09T23:45:16.372+0800	INFO	[publisher]	pipeline/retry.go:217	  done
2023-03-09T23:45:30.000+0800	INFO	[monitoring]	log/log.go:145	Non-zero metrics in the last 30s	{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":46},"total":{"ticks":108,"value":108},"user":{"ticks":62}},"handles":{"open":265},"info":{"ephemeral_id":"70a9c63d-221d-42d5-add4-b5122cacad24","uptime":{"ms":1140131}},"memstats":{"gc_next":17136864,"memory_alloc":8689424,"memory_total":40819768,"rss":4096},"runtime":{"goroutines":23}},"filebeat":{"harvester":{"open_files":0,"running":0}},"libbeat":{"config":{"module":{"running":0}},"pipeline":{"clients":1,"events":{"active":62,"retry":6}}},"registrar":{"states":{"current":1}}}}}
2023-03-09T23:46:00.000+0800	INFO	[monitoring]	log/log.go:145	Non-zero metrics in the last 30s	{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":46},"total":{"ticks":108,"value":108},"user":{"ticks":62}},"handles":{"open":265},"info":{"ephemeral_id":"70a9c63d-221d-42d5-add4-b5122cacad24","uptime":{"ms":1170131}},"memstats":{"gc_next":17136864,"memory_alloc":8752904,"memory_total":40883248},"runtime":{"goroutines":23}},"filebeat":{"harvester":{"open_files":0,"running":0}},"libbeat":{"config":{"module":{"running":0}},"pipeline":{"clients":1,"events":{"active":62}}},"registrar":{"states":{"current":1}}}}}
2023-03-09T23:46:17.392+0800	ERROR	[publisher_pipeline_output]	pipeline/output.go:154	Failed to connect to backoff(async(tcp://localhost:5044)): dial tcp 127.0.0.1:5044: connectex: No connection could be made because the target machine actively refused it.
2023-03-09T23:46:17.392+0800	INFO	[publisher_pipeline_output]	pipeline/output.go:145	Attempting to reconnect to backoff(async(tcp://localhost:5044)) with 27 reconnect attempt(s)
2023-03-09T23:46:17.392+0800	INFO	[publisher]	pipeline/retry.go:213	retryer: send wait signal to consumer
2023-03-09T23:46:17.392+0800	INFO	[publisher]	pipeline/retry.go:217	  done
2023-03-09T23:46:30.016+0800	INFO	[monitoring]	log/log.go:145	Non-zero metrics in the last 30s	{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":46},"total":{"ticks":108,"value":108},"user":{"ticks":62}},"handles":{"open":265},"info":{"ephemeral_id":"70a9c63d-221d-42d5-add4-b5122cacad24","uptime":{"ms":1200147}},"memstats":{"gc_next":17136864,"memory_alloc":8838496,"memory_total":40968840,"rss":8192},"runtime":{"goroutines":23}},"filebeat":{"harvester":{"open_files":0,"running":0}},"libbeat":{"config":{"module":{"running":0}},"pipeline":{"clients":1,"events":{"active":62,"retry":41}}},"registrar":{"states":{"current":1}}}}}
2023-03-09T23:47:00.001+0800	INFO	[monitoring]	log/log.go:145	Non-zero metrics in the last 30s	{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":46},"total":{"ticks":108,"value":108},"user":{"ticks":62}},"handles":{"open":263},"info":{"ephemeral_id":"70a9c63d-221d-42d5-add4-b5122cacad24","uptime":{"ms":1230131}},"memstats":{"gc_next":17134720,"memory_alloc":8585728,"memory_total":41037664,"rss":8192},"runtime":{"goroutines":23}},"filebeat":{"harvester":{"open_files":0,"running":0}},"libbeat":{"config":{"module":{"running":0}},"pipeline":{"clients":1,"events":{"active":62}}},"registrar":{"states":{"current":1}}}}}
2023-03-09T23:47:03.526+0800	ERROR	[publisher_pipeline_output]	pipeline/output.go:154	Failed to connect to backoff(async(tcp://localhost:5044)): dial tcp [::1]:5044: connectex: No connection could be made because the target machine actively refused it.
2023-03-09T23:47:03.526+0800	INFO	[publisher_pipeline_output]	pipeline/output.go:145	Attempting to reconnect to backoff(async(tcp://localhost:5044)) with 28 reconnect attempt(s)
2023-03-09T23:47:03.526+0800	INFO	[publisher]	pipeline/retry.go:213	retryer: send wait signal to consumer
2023-03-09T23:47:03.526+0800	INFO	[publisher]	pipeline/retry.go:217	  done
2023-03-09T23:47:30.005+0800	INFO	[monitoring]	log/log.go:145	Non-zero metrics in the last 30s	{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":46},"total":{"ticks":108,"value":108},"user":{"ticks":62}},"handles":{"open":265},"info":{"ephemeral_id":"70a9c63d-221d-42d5-add4-b5122cacad24","uptime":{"ms":1260136}},"memstats":{"gc_next":17134720,"memory_alloc":8682000,"memory_total":41133936,"rss":8192},"runtime":{"goroutines":23}},"filebeat":{"harvester":{"open_files":0,"running":0}},"libbeat":{"config":{"module":{"running":0}},"pipeline":{"clients":1,"events":{"active":62,"retry":3}}},"registrar":{"states":{"current":1}}}}}
2023-03-09T23:47:59.170+0800	ERROR	[publisher_pipeline_output]	pipeline/output.go:154	Failed to connect to backoff(async(tcp://localhost:5044)): dial tcp [::1]:5044: connectex: No connection could be made because the target machine actively refused it.
2023-03-09T23:47:59.170+0800	INFO	[publisher_pipeline_output]	pipeline/output.go:145	Attempting to reconnect to backoff(async(tcp://localhost:5044)) with 29 reconnect attempt(s)
2023-03-09T23:47:59.170+0800	INFO	[publisher]	pipeline/retry.go:213	retryer: send wait signal to consumer
2023-03-09T23:47:59.170+0800	INFO	[publisher]	pipeline/retry.go:217	  done
2023-03-09T23:48:00.003+0800	INFO	[monitoring]	log/log.go:145	Non-zero metrics in the last 30s	{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":46},"total":{"ticks":108,"value":108},"user":{"ticks":62}},"handles":{"open":266},"info":{"ephemeral_id":"70a9c63d-221d-42d5-add4-b5122cacad24","uptime":{"ms":1290132}},"memstats":{"gc_next":17134720,"memory_alloc":8756776,"memory_total":41208712,"rss":4096},"runtime":{"goroutines":24}},"filebeat":{"harvester":{"open_files":0,"running":0}},"libbeat":{"config":{"module":{"running":0}},"pipeline":{"clients":1,"events":{"active":62,"retry":3}}},"registrar":{"states":{"current":1}}}}}
2023-03-09T23:48:30.001+0800	INFO	[monitoring]	log/log.go:145	Non-zero metrics in the last 30s	{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":46},"total":{"ticks":108,"value":108},"user":{"ticks":62}},"handles":{"open":265},"info":{"ephemeral_id":"70a9c63d-221d-42d5-add4-b5122cacad24","uptime":{"ms":1320131}},"memstats":{"gc_next":17134720,"memory_alloc":8835968,"memory_total":41287904,"rss":16384},"runtime":{"goroutines":23}},"filebeat":{"harvester":{"open_files":0,"running":0}},"libbeat":{"config":{"module":{"running":0}},"pipeline":{"clients":1,"events":{"active":62}}},"registrar":{"states":{"current":1}}}}}
2023-03-09T23:48:37.776+0800	ERROR	[publisher_pipeline_output]	pipeline/output.go:154	Failed to connect to backoff(async(tcp://localhost:5044)): dial tcp [::1]:5044: connectex: No connection could be made because the target machine actively refused it.
2023-03-09T23:48:37.776+0800	INFO	[publisher_pipeline_output]	pipeline/output.go:145	Attempting to reconnect to backoff(async(tcp://localhost:5044)) with 30 reconnect attempt(s)
2023-03-09T23:48:37.776+0800	INFO	[publisher]	pipeline/retry.go:213	retryer: send wait signal to consumer
2023-03-09T23:48:37.776+0800	INFO	[publisher]	pipeline/retry.go:217	  done
2023-03-09T23:49:00.007+0800	INFO	[monitoring]	log/log.go:145	Non-zero metrics in the last 30s	{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":46},"total":{"ticks":108,"value":108},"user":{"ticks":62}},"handles":{"open":264},"info":{"ephemeral_id":"70a9c63d-221d-42d5-add4-b5122cacad24","uptime":{"ms":1350138}},"memstats":{"gc_next":17136896,"memory_alloc":8608952,"memory_total":41379040,"rss":12288},"runtime":{"goroutines":23}},"filebeat":{"harvester":{"open_files":0,"running":0}},"libbeat":{"config":{"module":{"running":0}},"pipeline":{"clients":1,"events":{"active":62,"retry":6}}},"registrar":{"states":{"current":1}}}}}
2023-03-09T23:49:14.838+0800	INFO	beater/filebeat.go:515	Stopping filebeat
2023-03-09T23:49:14.838+0800	INFO	beater/crawler.go:148	Stopping Crawler
2023-03-09T23:49:14.838+0800	INFO	beater/crawler.go:158	Stopping 1 inputs
2023-03-09T23:49:14.838+0800	INFO	[crawler]	beater/crawler.go:163	Stopping input: 9579789163401830746
2023-03-09T23:49:14.838+0800	INFO	input/input.go:136	input ticker stopped
2023-03-09T23:49:14.838+0800	INFO	beater/crawler.go:178	Crawler stopped
2023-03-09T23:49:14.838+0800	INFO	[registrar]	registrar/registrar.go:132	Stopping Registrar
2023-03-09T23:49:14.838+0800	INFO	[registrar]	registrar/registrar.go:166	Ending Registrar
2023-03-09T23:49:14.838+0800	INFO	[registrar]	registrar/registrar.go:137	Registrar stopped
2023-03-09T23:49:14.839+0800	INFO	[monitoring]	log/log.go:153	Total non-zero metrics	{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":46,"time":{"ms":46}},"total":{"ticks":108,"time":{"ms":108},"value":108},"user":{"ticks":62,"time":{"ms":62}}},"handles":{"open":263},"info":{"ephemeral_id":"70a9c63d-221d-42d5-add4-b5122cacad24","uptime":{"ms":1364970}},"memstats":{"gc_next":17136896,"memory_alloc":8690872,"memory_total":41460960,"rss":42414080},"runtime":{"goroutines":13}},"filebeat":{"events":{"active":65,"added":67,"done":2},"harvester":{"closed":2,"open_files":0,"running":0,"started":2}},"libbeat":{"config":{"module":{"running":0}},"output":{"type":"logstash"},"pipeline":{"clients":0,"events":{"active":62,"filtered":5,"published":62,"retry":584,"total":67}}},"registrar":{"states":{"current":1,"update":2},"writes":{"success":2,"total":2}},"system":{"cpu":{"cores":12}}}}}
2023-03-09T23:49:14.839+0800	INFO	[monitoring]	log/log.go:154	Uptime: 22m44.9702634s
2023-03-09T23:49:14.839+0800	INFO	[monitoring]	log/log.go:131	Stopping metrics logging.
2023-03-09T23:49:14.839+0800	INFO	instance/beat.go:456	filebeat stopped.
