2023-03-09T23:00:28.727+0800	INFO	instance/beat.go:640	Home path: [E:\code\云原生\git.imooc.com\dessple\pob] Config path: [E:\code\云原生\git.imooc.com\dessple\pob] Data path: [E:\code\云原生\git.imooc.com\dessple\pob\data] Logs path: [E:\code\云原生\git.imooc.com\dessple\pob\logs]
2023-03-09T23:00:28.728+0800	INFO	instance/beat.go:648	Beat ID: f781c3fd-0e4f-4897-a418-f8e76dba9b37
2023-03-09T23:00:28.729+0800	INFO	[beat]	instance/beat.go:976	Beat info	{"system_info": {"beat": {"path": {"config": "E:\\code\\云原生\\git.imooc.com\\dessple\\pob", "data": "E:\\code\\云原生\\git.imooc.com\\dessple\\pob\\data", "home": "E:\\code\\云原生\\git.imooc.com\\dessple\\pob", "logs": "E:\\code\\云原生\\git.imooc.com\\dessple\\pob\\logs"}, "type": "filebeat", "uuid": "f781c3fd-0e4f-4897-a418-f8e76dba9b37"}}}
2023-03-09T23:00:28.731+0800	INFO	[beat]	instance/beat.go:985	Build info	{"system_info": {"build": {"commit": "7aab6a9659749802201db8020c4f04b74cec2169", "libbeat": "7.9.3", "time": "2020-10-16T09:16:15.000Z", "version": "7.9.3"}}}
2023-03-09T23:00:28.731+0800	INFO	[beat]	instance/beat.go:988	Go runtime info	{"system_info": {"go": {"os":"windows","arch":"amd64","max_procs":12,"version":"go1.14.7"}}}
2023-03-09T23:00:28.816+0800	INFO	[beat]	instance/beat.go:992	Host info	{"system_info": {"host": {"architecture":"x86_64","boot_time":"2023-02-22T12:12:32.4+08:00","name":"DESKTOP-8K1IJ5A","ip":["fe80::2184:6ead:541:5295/64","169.254.23.90/16","fe80::9911:c532:6924:c868/64","172.31.144.1/20","fe80::5483:90c1:b30b:785e/64","169.254.244.105/16","fe80::35a9:1db8:a1f4:da6a/64","169.254.163.202/16","fe80::3318:2c57:4ae5:c3d8/64","192.168.142.1/24","fe80::bf70:9708:c69e:1b8/64","192.168.115.1/24","fd26:a241:87f4::d1f/128","fd26:a241:87f4:0:ce3d:e1bc:8bc0:100d/64","fd26:a241:87f4:0:6033:66cf:eaa9:9167/128","fd26:a241:87f4:0:d99c:5e73:3d70:9989/128","fd26:a241:87f4:0:f5d9:16bb:d810:9e93/128","fe80::ab2f:5bad:e890:55ea/64","192.168.1.128/24","fe80::99f4:b0e5:2e1d:d9a4/64","169.254.216.66/16","::1/128","127.0.0.1/8"],"kernel_version":"10.0.19041.2604 (WinBuild.160101.0800)","mac":["d8:bb:c1:4f:6c:c8","00:15:5d:fd:2b:60","e2:e1:a9:19:7a:8b","e0:e1:a9:19:7a:8b","00:50:56:c0:00:01","00:50:56:c0:00:08","e0:e1:a9:19:7a:8b","00:1a:7d:da:71:15"],"os":{"family":"windows","platform":"windows","name":"Windows 10 Pro","version":"10.0","major":10,"minor":0,"patch":0,"build":"19045.2604"},"timezone":"CST","timezone_offset_sec":28800,"id":"dc5c532d-a6b6-404d-a9b8-261c7f04c685"}}}
2023-03-09T23:00:28.816+0800	INFO	[beat]	instance/beat.go:1021	Process info	{"system_info": {"process": {"cwd": "E:\\code\\云原生\\git.imooc.com\\dessple\\pob", "exe": "D:\\filebeat-7.9.3-windows-x86_64\\filebeat.exe", "name": "filebeat.exe", "pid": 6796, "ppid": 26808, "start_time": "2023-03-09T23:00:28.365+0800"}}}
2023-03-09T23:00:28.816+0800	INFO	instance/beat.go:299	Setup Beat: filebeat; Version: 7.9.3
2023-03-09T23:00:28.817+0800	INFO	[publisher]	pipeline/module.go:113	Beat name: DESKTOP-8K1IJ5A
2023-03-09T23:00:28.818+0800	ERROR	fileset/modules.go:127	Not loading modules. Module directory not found: E:\code\云原生\git.imooc.com\dessple\pob\module
2023-03-09T23:00:28.818+0800	WARN	beater/filebeat.go:178	Filebeat is unable to load the Ingest Node pipelines for the configured modules because the Elasticsearch output is not configured/enabled. If you have already loaded the Ingest Node pipelines or are using Logstash pipelines, you can ignore this warning.
2023-03-09T23:00:28.819+0800	INFO	instance/beat.go:450	filebeat start running.
2023-03-09T23:00:28.819+0800	INFO	[monitoring]	log/log.go:118	Starting metrics logging every 30s
2023-03-09T23:00:28.820+0800	INFO	memlog/store.go:119	Loading data file of 'E:\code\云原生\git.imooc.com\dessple\pob\data\registry\filebeat' succeeded. Active transaction id=0
2023-03-09T23:00:28.820+0800	INFO	memlog/store.go:124	Finished loading transaction log file for 'E:\code\云原生\git.imooc.com\dessple\pob\data\registry\filebeat'. Active transaction id=2
2023-03-09T23:00:28.820+0800	WARN	beater/filebeat.go:381	Filebeat is unable to load the Ingest Node pipelines for the configured modules because the Elasticsearch output is not configured/enabled. If you have already loaded the Ingest Node pipelines or are using Logstash pipelines, you can ignore this warning.
2023-03-09T23:00:28.821+0800	INFO	[registrar]	registrar/registrar.go:109	States Loaded from registrar: 1
2023-03-09T23:00:28.821+0800	INFO	[crawler]	beater/crawler.go:71	Loading Inputs: 1
2023-03-09T23:00:28.822+0800	INFO	log/input.go:157	Configured paths: [E:\code\云原生\git.imooc.com\dessple\pob\*.log]
2023-03-09T23:00:28.822+0800	INFO	[crawler]	beater/crawler.go:141	Starting input (ID: 9579789163401830746)
2023-03-09T23:00:28.822+0800	INFO	[crawler]	beater/crawler.go:108	Loading and starting Inputs completed. Enabled inputs: 1
2023-03-09T23:00:28.830+0800	INFO	log/harvester.go:299	Harvester started for file: E:\code\云原生\git.imooc.com\dessple\pob\micro.log
2023-03-09T23:00:29.832+0800	INFO	[publisher]	pipeline/retry.go:219	retryer: send unwait signal to consumer
2023-03-09T23:00:29.832+0800	INFO	[publisher]	pipeline/retry.go:223	  done
2023-03-09T23:00:29.832+0800	INFO	[publisher_pipeline_output]	pipeline/output.go:143	Connecting to backoff(async(tcp://localhost:5044))
2023-03-09T23:00:35.659+0800	ERROR	[publisher_pipeline_output]	pipeline/output.go:154	Failed to connect to backoff(async(tcp://localhost:5044)): dial tcp 127.0.0.1:5044: connectex: No connection could be made because the target machine actively refused it.
2023-03-09T23:00:35.659+0800	INFO	[publisher_pipeline_output]	pipeline/output.go:145	Attempting to reconnect to backoff(async(tcp://localhost:5044)) with 1 reconnect attempt(s)
2023-03-09T23:00:35.659+0800	INFO	[publisher]	pipeline/retry.go:219	retryer: send unwait signal to consumer
2023-03-09T23:00:35.661+0800	INFO	[publisher]	pipeline/retry.go:223	  done
2023-03-09T23:00:42.508+0800	ERROR	[publisher_pipeline_output]	pipeline/output.go:154	Failed to connect to backoff(async(tcp://localhost:5044)): dial tcp [::1]:5044: connectex: No connection could be made because the target machine actively refused it.
2023-03-09T23:00:42.508+0800	INFO	[publisher_pipeline_output]	pipeline/output.go:145	Attempting to reconnect to backoff(async(tcp://localhost:5044)) with 2 reconnect attempt(s)
2023-03-09T23:00:42.508+0800	INFO	[publisher]	pipeline/retry.go:219	retryer: send unwait signal to consumer
2023-03-09T23:00:42.508+0800	INFO	[publisher]	pipeline/retry.go:223	  done
2023-03-09T23:00:51.839+0800	ERROR	[publisher_pipeline_output]	pipeline/output.go:154	Failed to connect to backoff(async(tcp://localhost:5044)): dial tcp [::1]:5044: connectex: No connection could be made because the target machine actively refused it.
2023-03-09T23:00:51.839+0800	INFO	[publisher_pipeline_output]	pipeline/output.go:145	Attempting to reconnect to backoff(async(tcp://localhost:5044)) with 3 reconnect attempt(s)
2023-03-09T23:00:51.839+0800	INFO	[publisher]	pipeline/retry.go:219	retryer: send unwait signal to consumer
2023-03-09T23:00:51.839+0800	INFO	[publisher]	pipeline/retry.go:223	  done
2023-03-09T23:00:58.832+0800	INFO	[monitoring]	log/log.go:145	Non-zero metrics in the last 30s	{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":187,"time":{"ms":187}},"total":{"ticks":265,"time":{"ms":265},"value":265},"user":{"ticks":78,"time":{"ms":78}}},"handles":{"open":234},"info":{"ephemeral_id":"6745ad84-f4d1-4f1a-9825-6e24f78ba005","uptime":{"ms":30246}},"memstats":{"gc_next":14834640,"memory_alloc":9253328,"memory_total":36779080,"rss":48832512},"runtime":{"goroutines":28}},"filebeat":{"events":{"active":31,"added":34,"done":3},"harvester":{"files":{"b5ad6b4d-5260-4da8-adcd-80f700fd117b":{"last_event_published_time":"2023-03-09T23:00:28.832Z","last_event_timestamp":"2023-03-09T23:00:28.832Z","name":"E:\\code\\云原生\\git.imooc.com\\dessple\\pob\\micro.log","read_offset":6096,"size":6096,"start_time":"2023-03-09T23:00:28.830Z"}},"open_files":1,"running":1,"started":1}},"libbeat":{"config":{"module":{"running":0}},"output":{"type":"logstash"},"pipeline":{"clients":1,"events":{"active":31,"filtered":3,"published":31,"retry":93,"total":34}}},"registrar":{"states":{"cleanup":1,"current":1,"update":3},"writes":{"success":3,"total":3}},"system":{"cpu":{"cores":12}}}}}
2023-03-09T23:01:11.004+0800	ERROR	[publisher_pipeline_output]	pipeline/output.go:154	Failed to connect to backoff(async(tcp://localhost:5044)): dial tcp [::1]:5044: connectex: No connection could be made because the target machine actively refused it.
2023-03-09T23:01:11.004+0800	INFO	[publisher_pipeline_output]	pipeline/output.go:145	Attempting to reconnect to backoff(async(tcp://localhost:5044)) with 4 reconnect attempt(s)
2023-03-09T23:01:11.004+0800	INFO	[publisher]	pipeline/retry.go:219	retryer: send unwait signal to consumer
2023-03-09T23:01:11.004+0800	INFO	[publisher]	pipeline/retry.go:223	  done
2023-03-09T23:01:28.821+0800	INFO	[monitoring]	log/log.go:145	Non-zero metrics in the last 30s	{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":187},"total":{"ticks":265,"value":265},"user":{"ticks":78}},"handles":{"open":233},"info":{"ephemeral_id":"6745ad84-f4d1-4f1a-9825-6e24f78ba005","uptime":{"ms":60236}},"memstats":{"gc_next":14834640,"memory_alloc":9355064,"memory_total":36880816,"rss":8192},"runtime":{"goroutines":28}},"filebeat":{"harvester":{"open_files":1,"running":1}},"libbeat":{"config":{"module":{"running":0}},"pipeline":{"clients":1,"events":{"active":31,"retry":31}}},"registrar":{"states":{"current":1}}}}}
2023-03-09T23:01:35.209+0800	ERROR	[publisher_pipeline_output]	pipeline/output.go:154	Failed to connect to backoff(async(tcp://localhost:5044)): dial tcp 127.0.0.1:5044: connectex: No connection could be made because the target machine actively refused it.
2023-03-09T23:01:35.209+0800	INFO	[publisher_pipeline_output]	pipeline/output.go:145	Attempting to reconnect to backoff(async(tcp://localhost:5044)) with 5 reconnect attempt(s)
2023-03-09T23:01:35.209+0800	INFO	[publisher]	pipeline/retry.go:219	retryer: send unwait signal to consumer
2023-03-09T23:01:35.209+0800	INFO	[publisher]	pipeline/retry.go:223	  done
2023-03-09T23:01:58.831+0800	INFO	[monitoring]	log/log.go:145	Non-zero metrics in the last 30s	{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":187},"total":{"ticks":265,"value":265},"user":{"ticks":78}},"handles":{"open":233},"info":{"ephemeral_id":"6745ad84-f4d1-4f1a-9825-6e24f78ba005","uptime":{"ms":90246}},"memstats":{"gc_next":14834640,"memory_alloc":9448112,"memory_total":36973864,"rss":28672},"runtime":{"goroutines":28}},"filebeat":{"harvester":{"open_files":1,"running":1}},"libbeat":{"config":{"module":{"running":0}},"pipeline":{"clients":1,"events":{"active":31,"retry":31}}},"registrar":{"states":{"current":1}}}}}
2023-03-09T23:02:28.821+0800	INFO	[monitoring]	log/log.go:145	Non-zero metrics in the last 30s	{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":187},"total":{"ticks":265,"value":265},"user":{"ticks":78}},"handles":{"open":233},"info":{"ephemeral_id":"6745ad84-f4d1-4f1a-9825-6e24f78ba005","uptime":{"ms":120235}},"memstats":{"gc_next":15951024,"memory_alloc":9321416,"memory_total":37038768,"rss":233472},"runtime":{"goroutines":28}},"filebeat":{"harvester":{"open_files":1,"running":1}},"libbeat":{"config":{"module":{"running":0}},"pipeline":{"clients":1,"events":{"active":31}}},"registrar":{"states":{"current":1}}}}}
2023-03-09T23:02:29.694+0800	ERROR	[publisher_pipeline_output]	pipeline/output.go:154	Failed to connect to backoff(async(tcp://localhost:5044)): dial tcp [::1]:5044: connectex: No connection could be made because the target machine actively refused it.
2023-03-09T23:02:29.694+0800	INFO	[publisher_pipeline_output]	pipeline/output.go:145	Attempting to reconnect to backoff(async(tcp://localhost:5044)) with 6 reconnect attempt(s)
2023-03-09T23:02:29.694+0800	INFO	[publisher]	pipeline/retry.go:219	retryer: send unwait signal to consumer
2023-03-09T23:02:29.694+0800	INFO	[publisher]	pipeline/retry.go:223	  done
2023-03-09T23:02:58.820+0800	INFO	[monitoring]	log/log.go:145	Non-zero metrics in the last 30s	{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":187},"total":{"ticks":265,"value":265},"user":{"ticks":78}},"handles":{"open":233},"info":{"ephemeral_id":"6745ad84-f4d1-4f1a-9825-6e24f78ba005","uptime":{"ms":150235}},"memstats":{"gc_next":15951024,"memory_alloc":8063688,"memory_total":37131424,"rss":-3596288},"runtime":{"goroutines":28}},"filebeat":{"harvester":{"open_files":1,"running":1}},"libbeat":{"config":{"module":{"running":0}},"pipeline":{"clients":1,"events":{"active":31,"retry":31}}},"registrar":{"states":{"current":1}}}}}
2023-03-09T23:03:26.638+0800	ERROR	[publisher_pipeline_output]	pipeline/output.go:154	Failed to connect to backoff(async(tcp://localhost:5044)): dial tcp 127.0.0.1:5044: connectex: No connection could be made because the target machine actively refused it.
2023-03-09T23:03:26.638+0800	INFO	[publisher_pipeline_output]	pipeline/output.go:145	Attempting to reconnect to backoff(async(tcp://localhost:5044)) with 7 reconnect attempt(s)
2023-03-09T23:03:26.638+0800	INFO	[publisher]	pipeline/retry.go:219	retryer: send unwait signal to consumer
2023-03-09T23:03:26.638+0800	INFO	[publisher]	pipeline/retry.go:223	  done
2023-03-09T23:03:28.820+0800	INFO	[monitoring]	log/log.go:145	Non-zero metrics in the last 30s	{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":187},"total":{"ticks":265,"value":265},"user":{"ticks":78}},"handles":{"open":236},"info":{"ephemeral_id":"6745ad84-f4d1-4f1a-9825-6e24f78ba005","uptime":{"ms":180234}},"memstats":{"gc_next":15951024,"memory_alloc":8151168,"memory_total":37218904,"rss":4096},"runtime":{"goroutines":29}},"filebeat":{"harvester":{"open_files":1,"running":1}},"libbeat":{"config":{"module":{"running":0}},"pipeline":{"clients":1,"events":{"active":31,"retry":31}}},"registrar":{"states":{"current":1}}}}}
2023-03-09T23:03:58.819+0800	INFO	[monitoring]	log/log.go:145	Non-zero metrics in the last 30s	{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":187},"total":{"ticks":265,"value":265},"user":{"ticks":78}},"handles":{"open":235},"info":{"ephemeral_id":"6745ad84-f4d1-4f1a-9825-6e24f78ba005","uptime":{"ms":210234}},"memstats":{"gc_next":15951024,"memory_alloc":8227240,"memory_total":37294976},"runtime":{"goroutines":28}},"filebeat":{"harvester":{"open_files":1,"running":1}},"libbeat":{"config":{"module":{"running":0}},"pipeline":{"clients":1,"events":{"active":31}}},"registrar":{"states":{"current":1}}}}}
2023-03-09T23:04:22.022+0800	ERROR	[publisher_pipeline_output]	pipeline/output.go:154	Failed to connect to backoff(async(tcp://localhost:5044)): dial tcp [::1]:5044: connectex: No connection could be made because the target machine actively refused it.
2023-03-09T23:04:22.022+0800	INFO	[publisher_pipeline_output]	pipeline/output.go:145	Attempting to reconnect to backoff(async(tcp://localhost:5044)) with 8 reconnect attempt(s)
2023-03-09T23:04:22.022+0800	INFO	[publisher]	pipeline/retry.go:219	retryer: send unwait signal to consumer
2023-03-09T23:04:22.022+0800	INFO	[publisher]	pipeline/retry.go:223	  done
2023-03-09T23:04:28.819+0800	INFO	[monitoring]	log/log.go:145	Non-zero metrics in the last 30s	{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":187},"total":{"ticks":265,"value":265},"user":{"ticks":78}},"handles":{"open":237},"info":{"ephemeral_id":"6745ad84-f4d1-4f1a-9825-6e24f78ba005","uptime":{"ms":240234}},"memstats":{"gc_next":15951024,"memory_alloc":8310976,"memory_total":37378712},"runtime":{"goroutines":28}},"filebeat":{"harvester":{"open_files":1,"running":1}},"libbeat":{"config":{"module":{"running":0}},"pipeline":{"clients":1,"events":{"active":31,"retry":31}}},"registrar":{"states":{"current":1}}}}}
2023-03-09T23:04:58.829+0800	INFO	[monitoring]	log/log.go:145	Non-zero metrics in the last 30s	{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":187},"total":{"ticks":265,"value":265},"user":{"ticks":78}},"handles":{"open":240},"info":{"ephemeral_id":"6745ad84-f4d1-4f1a-9825-6e24f78ba005","uptime":{"ms":270244}},"memstats":{"gc_next":15888576,"memory_alloc":7978416,"memory_total":37452776,"rss":-2121728},"runtime":{"goroutines":28}},"filebeat":{"harvester":{"open_files":1,"running":1}},"libbeat":{"config":{"module":{"running":0}},"pipeline":{"clients":1,"events":{"active":31}}},"registrar":{"states":{"current":1}}}}}
2023-03-09T23:05:24.501+0800	ERROR	[publisher_pipeline_output]	pipeline/output.go:154	Failed to connect to backoff(async(tcp://localhost:5044)): dial tcp 127.0.0.1:5044: connectex: No connection could be made because the target machine actively refused it.
2023-03-09T23:05:24.501+0800	INFO	[publisher_pipeline_output]	pipeline/output.go:145	Attempting to reconnect to backoff(async(tcp://localhost:5044)) with 9 reconnect attempt(s)
2023-03-09T23:05:24.501+0800	INFO	[publisher]	pipeline/retry.go:219	retryer: send unwait signal to consumer
2023-03-09T23:05:24.501+0800	INFO	[publisher]	pipeline/retry.go:223	  done
2023-03-09T23:05:28.820+0800	INFO	[monitoring]	log/log.go:145	Non-zero metrics in the last 30s	{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":187},"total":{"ticks":265,"value":265},"user":{"ticks":78}},"handles":{"open":244},"info":{"ephemeral_id":"6745ad84-f4d1-4f1a-9825-6e24f78ba005","uptime":{"ms":300235}},"memstats":{"gc_next":15888576,"memory_alloc":8298696,"memory_total":37773056,"rss":278528},"runtime":{"goroutines":28}},"filebeat":{"events":{"active":1,"added":1},"harvester":{"files":{"b5ad6b4d-5260-4da8-adcd-80f700fd117b":{"last_event_published_time":"2023-03-09T23:05:03.995Z","last_event_timestamp":"2023-03-09T23:05:03.995Z","read_offset":107,"size":107}},"open_files":1,"running":1}},"libbeat":{"config":{"module":{"running":0}},"pipeline":{"clients":1,"events":{"active":32,"published":1,"retry":31,"total":1}}},"registrar":{"states":{"current":1}}}}}
2023-03-09T23:05:58.825+0800	INFO	[monitoring]	log/log.go:145	Non-zero metrics in the last 30s	{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":187},"total":{"ticks":265,"value":265},"user":{"ticks":78}},"handles":{"open":244},"info":{"ephemeral_id":"6745ad84-f4d1-4f1a-9825-6e24f78ba005","uptime":{"ms":330240}},"memstats":{"gc_next":15888576,"memory_alloc":8408512,"memory_total":37882872},"runtime":{"goroutines":28}},"filebeat":{"events":{"active":2,"added":2},"harvester":{"files":{"b5ad6b4d-5260-4da8-adcd-80f700fd117b":{"last_event_published_time":"2023-03-09T23:05:39.004Z","last_event_timestamp":"2023-03-09T23:05:39.004Z","read_offset":819}},"open_files":1,"running":1}},"libbeat":{"config":{"module":{"running":0}},"pipeline":{"clients":1,"events":{"active":34,"published":2,"total":2}}},"registrar":{"states":{"current":1}}}}}
2023-03-09T23:06:16.275+0800	ERROR	[publisher_pipeline_output]	pipeline/output.go:154	Failed to connect to backoff(async(tcp://localhost:5044)): dial tcp 127.0.0.1:5044: connectex: No connection could be made because the target machine actively refused it.
2023-03-09T23:06:16.275+0800	INFO	[publisher_pipeline_output]	pipeline/output.go:145	Attempting to reconnect to backoff(async(tcp://localhost:5044)) with 10 reconnect attempt(s)
2023-03-09T23:06:16.275+0800	INFO	[publisher]	pipeline/retry.go:219	retryer: send unwait signal to consumer
2023-03-09T23:06:16.275+0800	INFO	[publisher]	pipeline/retry.go:223	  done
2023-03-09T23:06:18.236+0800	INFO	beater/filebeat.go:515	Stopping filebeat
